### ISSUE TITLE
Audio sometimes not working and some of the system preference won't save

### ISSUE THREAD

**Issue by FAL0258** [wgjas2/MSI-Prestige-15-Hackintosh#9]
Sometimes audio not working when using internal speakers, until I plug earphone and eject it. It's still not working even I installed both combojack and jackfix

And some part of system preference back to default. This problem may appear after failure boot. There is a low possibility that it fails to boot to big sur.

**Comment by wgjas2** [comment]
yes, problem still exist, but i can't find a solution.

**Comment by AndryX19** [comment]
Hi, I solve the audio problem, simply open the config and shift the two declaration of intel bluetooth kexts almost at the and of the list, before the memoryfix.... kext (the last one of kexts list). The problem of intel bluetooth that not work still remain, unfortunately, I think that the problem is a conflict with new version of itwml intel wifi kext. For me everything work good except bluetooth.
